name: module_integration
channels:
    - conda-forge
    - bioconda
dependencies:
    - python=3.12
    - flake8=3.8.3
    - snakemake-minimal=8.18
    # - graphviz=2.50.0
    - pandas
    - numpy<2.0.0
    - xlrd
    - geopandas
    - pandera
    - pyarrow>=19.0.1
    - xarray
    - rioxarray
    - matplotlib
    - pycountry
    - jupyter
    - glpk
    - pip
    - pip:
        - -e ./lib
        - git+https://github.com/jnnr/gregor.git
        - git+https://github.com/jnnr/calliope.git@feature-allow-node-params-on-links-0.7.0.dev5
        - -e ../downscaling
        - -e ../good-plots
variables:
    SNAKEMAKE_PROFILE: ./profiles/default
